alert('😍 Los nombres de los símbolos químicos y demás texto aparecerá sin acento debido a que el tipo de letra no acepta caracteres con acento');
alert('😍 No olvides respetar mayúsculas y minúsculas');

function adivinarElemento(simbolo) {
var ElementosQuimicos = {
"Ac":"Actinio",
"Ag":"Plata",
"Al":"Aluminio",
"Am":"Americio",
"Ar":"Argon",
"As":"Arsenico",
"At":"Astato",
"Au":"Oro",
"B":"Boro",
"Ba":"Bario",
"Be":"Berilio",
"Bh":"Bohrio",
"Bi":"Bismuto",
"Bk":"Berkelio",
"Br":"Bromo",
"C":"Carbono",
"Ca":"Calcio",
"Cd":"Cadmio",
"Ce":"Cerio",
"Cf":"Californio",
"Cl":"Cloro",
"Cm":"Curio",
"Cn":"Copernicio",
"Co":"Cobalto",
"Cr":"Cromo",
"Cs":"Cesio",
"Cu":"Cobre",
"Db":"Dubnio",
"Ds":"Darmstatio",
"Dy":"Disprosio",
"Er":"Erbio",
"Es":"Einstenio",
"Eu":"Europio",
"F":"Fluor",
"Fe":"Hierro",
"Fl":"Flerovio",
"Fm":"Fermio",
"Fr":"Francio",
"Ga":"Galio",
"Gd":"Gadolinio",
"Ge":"Germanio",
"H":"Hidrogeno",
"He":"Helio",
"Hf":"Hafnio",
"Hg":"Mercurio",
"Ho":"Holmio",
"Hs":"Hasio",
"I":"Yodo",
"In":"Indio",
"Ir":"Iridio",
"K":"Potasio",
"Kr":"Kripton",
"La":"Lantano",
"Li":"Litio",
"Lr":"Lawrencio",
"Lu":"Lutecio",
"Lv":"Livermorio",
"Mc":"Moscovio",
"Md":"Mendelevio",
"Mg":"Magnesio",
"Mn":"Manganeso",
"Mo":"Molibdeno",
"Mt":"Meitnerio",
"N":"Nitrogeno",
"Na":"Sodio",
"Nb":"Niobio",
"Nd":"Neodimio",
"Ne":"Neon",
"Nh":"Nihonio",
"Ni":"Niquel",
"No":"Nobelio",
"Np":"Neptunio",
"O":"Oxigeno",
"Og":"Oganesson",
"Os":"Osmio",
"P":"Fosforo",
"Pa":"Protactinio",
"Pb":"Plomo",
"Pd":"Paladio",
"Pm":"Prometio",
"Po":"Polonio",
"Pr":"Praseodimio",
"Pt":"Platino",
"Pu":"Plutonio",
"Ra":"Radio",
"Rb":"Rubidio",
"Re":"Renio",
"Rf":"Rutherfordio",
"Rg":"Roentgenio",
"Rh":"Rodio",
"Rn":"Radon",
"Ru":"Rutenio",
"S":"Azufre",
"Sb":"Antimonio",
"Sc":"Escandio",
"Se":"Selenio",
"Sg":"Seaborgio",
"Si":"Silicio",
"Sm":"Samario",
"Sn":"Estaño",
"Sr":"Estroncio",
"Ta":"Tantalo",
"Tb":"Terbio",
"Tc":"Tecnecio",
"Te":"Telurio",
"Th":"Torio",
"Ti":"Titanio",
"Tl":"Talio",
"Tm":"Tulio",
"Ts":"Teneso",
"U":"Uranio",
"V":"Vanadio",
"W":"Wolframio",
"Xe":"Xenon",
"Y":"Itrio",
"Yb":"Iterbio",
"Zn":"Zinc",
"Zr":"Circonio",

    };

var resultado = document.getElementById("resultado");

if (ElementosQuimicos [simbolo] == undefined){
    resultado.innerHTML = "No es un elemento quimico";
} else {
    
resultado.innerHTML = "Felicidades! ... encontraste al " + ElementosQuimicos [simbolo];
}


}



